server:
  port: 8087


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
         id: user-service
         uri: lb://user-service
         predicates: Path=/user/**
      routes[1]:
         id: worker-service
         uri: lb://worker-service
         predicates: Path=/worker/**
      routes[2]:
         id: demo-service
         uri: lb://demo-service
         predicates: Path=/worker/**


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE



