server:
  port: 0

spring:
  application:
    name: user-service

  main:
    allow-bean-definition-overriding=true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true